### ISSUE TITLE
where to send MacOS 64-bit binary

### ISSUE THREAD

**Issue by sanderjo** [pmachapman/unrar#1]
I've compiled on MacOS 64-bit which is not availabe on https://www.rarlab.com/ (AFAIK). Where can I send the binary?
```
$ file unrar
unrar: Mach-O 64-bit executable x86_64
```

The readme.txt says

```
2. Unrar binaries

   If you compiled Unrar for OS, which is not present in "Downloads"
   and "RAR extras" on www.rarlab.com, we will appreciate if you send
   us the compiled executable to place it to our site.
```

**Comment by pmachapman** [comment]
Hi,
You may want to email their support or developer email addresses listed at https://rarlab.com/feedback.htm.

NOTE: I am not affiliated with win.rar GmbH in anyway - I put these files up on GitHub as a convenience.

Thanks,


Peter
