### ISSUE TITLE
Please describe supported RAR version(s)

### ISSUE THREAD

**Issue by davidhedlund** [pmachapman/unrar#10]
https://github.com/pmachapman/unrar does not inform which RAR versions that are supported.

For example, unrar-free  "plain RAR 2.0 supported (normal and solid archives), SFX and Volumes are NOT supported!"
* https://github.com/Lesik/unrar-free/issues/1

**Comment by aonez** [comment]
This is an `unrar` (from RARLAB, Alexander Roshal) source code mirror.

**Comment by davidhedlund** [comment]
Oh, sorry.

Can you please add RAR sample files to all versions at https://www.rarlab.com/?

That will enable people to find out which file version that are incompatible with file archivers when they are comparing them with unrar.

**Comment by davidhedlund** [comment]
Examples: rar4.0.rar, rar5.0.rar

**Comment by pmachapman** [comment]
This is just a mirror of the unrar source code from rarlab.com.

I am not affiliated with win.rar GmbH in any way.

**Comment by davidhedlund** [comment]
> This is just a mirror of the unrar source code from rarlab.com.
> 
> I am not affiliated with win.rar GmbH in any way.

Oh, sorry. Thank you for telling me.
